-- ============================================================
-- AUDITORIA DE FRETES - SUPABASE
-- Cole este SQL no SQL Editor do seu projeto Supabase.
-- ============================================================

create table if not exists public.fretes (
    id bigint generated by default as identity primary key,
    cte text not null,
    nf text,
    origem text,
    destino text,

    peso_calculado numeric default 0,
    peso_utilizado numeric default 0,

    valor_merc_calculado numeric default 0,
    valor_merc_utilizado numeric default 0,

    frete_peso_calculado numeric default 0,
    frete_peso_utilizado numeric default 0,

    gris_adv_calculado numeric default 0,
    gris_adv_utilizado numeric default 0,

    pedagio_calculado numeric default 0,
    pedagio_utilizado numeric default 0,

    tx_tde_calculada numeric default 0,
    tx_tde_utilizado numeric default 0,

    taxa_cte_calculado numeric default 0,
    taxa_cte_utilizado numeric default 0,

    icms_calculado numeric default 0,
    icms_utilizado numeric default 0,

    total_calculado numeric default 0,
    total_utilizado numeric default 0,

    status text not null default 'PENDENTE'
        check (status in ('PENDENTE', 'PROCEDENTE', 'NAO_PROCEDENTE')),

    comentario text default '',
    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now()
);

create table if not exists public.manifestacoes (
    id bigint generated by default as identity primary key,
    frete_id bigint not null references public.fretes(id) on delete cascade,
    status text not null
        check (status in ('PROCEDENTE', 'NAO_PROCEDENTE')),
    comentario text not null,
    criado_em timestamptz not null default now(),
    usuario_id uuid references auth.users(id)
);

-- Índices úteis
create index if not exists idx_fretes_cte
    on public.fretes(cte);

create index if not exists idx_fretes_status
    on public.fretes(status);

create index if not exists idx_manifestacoes_frete_id
    on public.manifestacoes(frete_id);

-- ============================================================
-- SEGURANÇA
-- Somente usuários autenticados podem consultar/alterar os dados.
-- ============================================================

alter table public.fretes enable row level security;
alter table public.manifestacoes enable row level security;

drop policy if exists "fretes_select_authenticated" on public.fretes;
create policy "fretes_select_authenticated"
on public.fretes
for select
to authenticated
using (true);

drop policy if exists "fretes_update_authenticated" on public.fretes;
create policy "fretes_update_authenticated"
on public.fretes
for update
to authenticated
using (true)
with check (true);

drop policy if exists "fretes_insert_authenticated" on public.fretes;
create policy "fretes_insert_authenticated"
on public.fretes
for insert
to authenticated
with check (true);

drop policy if exists "manifestacoes_select_authenticated" on public.manifestacoes;
create policy "manifestacoes_select_authenticated"
on public.manifestacoes
for select
to authenticated
using (true);

drop policy if exists "manifestacoes_insert_authenticated" on public.manifestacoes;
create policy "manifestacoes_insert_authenticated"
on public.manifestacoes
for insert
to authenticated
with check (true);

-- Mantém o usuário que fez a manifestação.
create or replace function public.registrar_usuario_manifestacao()
returns trigger
language plpgsql
security invoker
as $$
begin
    new.usuario_id := auth.uid();
    return new;
end;
$$;

drop trigger if exists trg_manifestacao_usuario on public.manifestacoes;
create trigger trg_manifestacao_usuario
before insert on public.manifestacoes
for each row
execute function public.registrar_usuario_manifestacao();

-- ============================================================
-- OPCIONAL: para importar os dados iniciais, use CSV/Excel
-- pelo Table Editor do Supabase depois de criar a tabela.
-- ============================================================
